# Generated by Django 4.0.4 on 2022-05-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.country')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.sector')),
            ],
        ),
    ]
